version: '3.6'
services:
  cache:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1972:1972
      - 57772:57772
    volumes:
      - ./:/opt/cacheapp
      - ../:/external
